### ISSUE TITLE
Create UI elements for copying join link.

### ISSUE THREAD

**Issue by TheTeaCat** [onfe/Picto#16]

**Comment by onfe** [comment]
I've marked this as addressed as it functions as expected, but I note that I may want to tweak the styling to make it more interactive in the future.

**Comment by TheTeaCat** [comment]
@onfe I'm getting no visual feedback that the button actually does anything? Seems a bit odd for it to not display a little "Copied!" message, or at least flash like the keyboard button.

**Comment by onfe** [comment]
Whoops, that's on me, the button styling classes need an overhaul to allow a popup similar to the one you're describing. The way buttons and button groups are currently handled makes this very tricky.

I'll create a separate issue, and making this button provide visual feedback will be part of that overhaul.
