### ISSUE TITLE
Add server side message IDs to prevent incorrect ordering.

### ISSUE THREAD

**Issue by onfe** [onfe/Picto#24]

**Comment by PedantiCat** [comment]
To clarify, we just want IDs for messages? Not anything else, like announcements, room join/leave etc.?

**Comment by TheTeaCat** [comment]
Added times to the websocket protocol in the event wrapper. Not sure if yet used client side?
@onfe

**Comment by onfe** [comment]
Commit 699166938e8af3c3e176d4df4083f86496d1c3c7 addresses this issue, by sorting by the timestamp. Messages sent within 1ms of each other may end up out of order, however.

**Comment by TheTeaCat** [comment]
Messages may also end up out of order for `Alice` if:

 1. `Alice` sends a message
 2. `Bob` sends a message
 3. The server receives `Bob`'s message
 4. The server receives `Alice`'s message.

`Bob`'s message will appear after `Alice`'s message from the perspective of `Alice`, but for everyone else, `Bob`'s message will appear before `Alice`'s message.

However, for such behavior to likely occur `Alice` would have to have a considerably higher ping than `Bob` to allow `Bob` a big enough time window to send a message and cause this effect.
