### ISSUE TITLE
Messages need to be associated with users differently.

### ISSUE THREAD

**Issue by TheTeaCat** [onfe/Picto#27]
If "client A" joins a room, sends a message, leaves and then "client B" joins, the message will appear to have been sent by "client B", not "client A".

**Comment by PedantiCat** [comment]
Discussed:
 - User indices need to be retained for colour management, they'll be renamed to "colour indices".
 - No association needs to be kept after message send between the user and the message as we don't intend to handle name changing (at least not name changing that has any effect on the message history); consequently, messages will just become associated with the username of the sender and not their user index (now "colour index").

**Comment by PedantiCat** [comment]
The user index of the sender still needs to be kept internally for use by the server when redistributing messages, so this fix shouldn't cause any issues; the server now sends the username of the user that sent the message at the time they sent it; the "userIndex" is still sent along with it. When this change is handled client side by @onfe I'll remove it as it's essentially useless information.

**Comment by onfe** [comment]
Some kind of index will still be required for assigning colours.

**Comment by PedantiCat** [comment]
Fair enough, I'll leave "userIndex" in as is then. Would be sensible to rename it to "colourIndex".

**Comment by onfe** [comment]
For compatibility, add `colourIndex`, being the same as `userIndex`. Then once client is switched over, remove `userIndex`. Alternatively, rename & break it now, fix later.

**Comment by onfe** [comment]
As of [948d253](https://github.com/onfe/Picto/commit/948d253813468a04e4da9a564028c4f57e3991e4) the client is ready for the transition.
