### ISSUE TITLE
Text isn't overlayed atop drawn elements properly.

### ISSUE THREAD

**Issue by TheTeaCat** [onfe/Picto#32]
If I draw onto the canvas with the black pen, then write over the drawing with rainbow text, the text is hidden behind the drawing made with the black pen instead of being drawn atop it (as it should be).

**Comment by PedantiCat** [comment]
This is fixed on the cam branch. Will be resolved when this feature makes its way to master.

**Comment by TheTeaCat** [comment]
Cam branch might be abandoned, fixed on dev.
