### ISSUE TITLE
Join error codes / messages

### ISSUE THREAD

**Issue by onfe** [onfe/Picto#49]
Send a text error string on every error.

**Comment by TheTeaCat** [comment]
Awaiting client-side implementation of current error responses.

**Comment by onfe** [comment]
WebSocket spec [doesn't allow HTTP status](https://stackoverflow.com/questions/21762596/how-to-read-status-code-from-rejected-websocket-opening-handshake-with-javascrip) codes when failing to make a connection, citing 'Security Reasons'. Instead intended behaviour is to open the connection then immediately close the connection with a custom [code](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent).

**Comment by TheTeaCat** [comment]
78ba56c43e5fe9a519188b2b13ee280c15bb7381 I believe makes the appropriate changes. We need to agree on error codes, however.

**Comment by TheTeaCat** [comment]
720cfcaab99f01c9eb4bdb7f2ca68eea8797960e adds error codes to [API.md](https://github.com/onfe/Picto/blob/720cfcaab99f01c9eb4bdb7f2ca68eea8797960e/API.md)
