### ISSUE TITLE
Modify UI to display that Picto is offline/unreachable without requiring user interaction

### ISSUE THREAD

**Issue by TheTeaCat** [onfe/Picto#69]
Currently, you have to enter a username and try to join a room before getting a "can't connect to Picto" message. 

It's not very nice UX; kind of annoying having put the effort in to create a username to find that Picto is offline anyway.

**Comment by onfe** [comment]
I've added an experimental version of this in 4775d6130dac1c3ccba2a14a6af75dae4a64cec1 . It's very difficult to test without pushing to prod, but runs just fine when using devtools to force offline.
