### ISSUE TITLE
Refactor server logging.

### ISSUE THREAD

**Issue by PedantiCat** [onfe/Picto#7]
Make more human readable.

- Hash long values (e.g. messages) so you can see if things are changing.

**Comment by PedantiCat** [comment]
Can't remember exactly what was needed here, iirc it was just logging client messages as hex strings instead of just truncating them? If so, this can close.

**Comment by onfe** [comment]
Ideally the type of event, timestamp and some info that would vary depending on the type of event eg:

```
[MSG] 2019/12/22 21:22:59 - Sent (message hash) to room 23
```
As long as it's easy to scan through in a large log file, and the data before the ` - ` is all the same length, it would be ideal.

**Comment by PedantiCat** [comment]
The golang lib I'm using for logging (literally, "log"), handles timestamps already. 
I guess I'll just scrub through everything and make it conform to something like the following format, then close:

`2019/12/24 21:39:31 [MESSAGE] - Distributed to room 'room id': [message hash]
`
