### ISSUE TITLE
Fix funky scrolling behaviour

### ISSUE THREAD

**Issue by TheTeaCat** [onfe/Picto#70]
"Use a new CSS flag to anchor the scrollbar on the opposite end"

"Safari doesn't support the new flag yet, but it does support scrolling on column reverse, so you just media query it"

**Comment by onfe** [comment]
I'm going to roll back these commits, revert to using `column-reverse` on all browsers except Firefox. This should solve the odd scrolling on Chrome in the most obvious way, assuming browser detection works correctly.
