### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by TheTeaCat** [onfe/Picto#77]

**Comment by TheTeaCat** [comment]
nope not getting involved in this one no thanks bye bye that's a lotta hassle

**Comment by onfe** [comment]
A fat commit (fb4250f55c9d8e0c0217487c965408748099ed53) brought most of dark mode in, still some polishing to do before this can be called done.

**Comment by TheTeaCat** [comment]
I'll implement a button to enable/disable dark mode later if that's cool. 

Done the same thing over at [lastfm-tag-cloud](https://github.com/TheTeaCat/lastfm-tag-cloud).

**Comment by TheTeaCat** [comment]
Announcements are pure black blobs in the message history sidebar. I've used some css filters to manipulate the colours into being more visible for now.
